from fastapi import (
    APIRouter,
    Depends,
     Query,
    HTTPException,
)
from sqlalchemy import (
    case,
    desc,
    func,
    select,
)
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.connection import get_db
from datetime import datetime, timedelta, timezone
from app.database.schemas import (
    Alert,
    Incident,
    MaintenanceOrder,
    Permit,
    PlantZone,
    ResponseAction,
    RiskEvent,
    Worker,
    WorkerLocation,
    WorkerPPEStatus,
)

router = APIRouter(
    prefix="/dashboard",
    tags=["Dashboard"],
)
def normalize_value(value) -> str:
    """
    Converts strings or enum values into a lowercase string.
    """

    if value is None:
        return ""

    if hasattr(value, "value"):
        value = value.value

    return str(value).strip().lower()


def contains_machine_anomaly(risk_event: RiskEvent) -> bool:
    """
    Checks whether a risk event contains machine-anomaly
    information generated by the compound-risk workflow.
    """

    predicted_event = normalize_value(
        getattr(
            risk_event,
            "predicted_event",
            None,
        )
    )

    explanation = normalize_value(
        getattr(
            risk_event,
            "explanation",
            None,
        )
    )

    contributing_factors = normalize_value(
        getattr(
            risk_event,
            "contributing_factors",
            None,
        )
    )

    anomaly_keywords = [
        "machine anomaly",
        "abnormal machine",
        "machine behaviour",
        "machine behavior",
        "equipment anomaly",
        "abnormal equipment",
        "anomaly score",
    ]

    combined_text = " ".join(
        [
            predicted_event,
            explanation,
            contributing_factors,
        ]
    )

    return any(
        keyword in combined_text
        for keyword in anomaly_keywords
    )


def get_machine_anomaly_score(
    risk_event: RiskEvent,
) -> float | None:
    """
    Extracts the machine-anomaly score when the RiskEvent
    model already stores it as a separate field.

    Returns None when it is only present inside explanation
    text.
    """

    possible_fields = [
        "anomaly_score",
        "machine_anomaly_score",
        "machine_score",
    ]

    for field_name in possible_fields:
        value = getattr(
            risk_event,
            field_name,
            None,
        )

        if value is not None:
            try:
                return round(
                    float(value),
                    2,
                )
            except (TypeError, ValueError):
                return None

    return None


def get_event_timestamp(
    risk_event: RiskEvent,
):
    """
    Returns the available timestamp field from RiskEvent.
    """

    possible_fields = [
        "created_at",
        "timestamp",
        "event_time",
        "recorded_at",
        "updated_at",
    ]

    for field_name in possible_fields:
        value = getattr(
            risk_event,
            field_name,
            None,
        )

        if value is not None:
            return value

    return None


def get_maintenance_timestamp(
    maintenance: MaintenanceOrder,
):
    """
    Returns the latest available maintenance timestamp.
    """

    possible_fields = [
        "actual_end",
        "actual_start",
        "scheduled_end",
        "scheduled_start",
        "reported_time",
    ]
    for field_name in possible_fields:
        value = getattr(
            maintenance,
            field_name,
            None,
        )

        if value is not None:
            return value

    return None


def get_maintenance_due_date(
    maintenance: MaintenanceOrder,
):
    """
    Returns the maintenance due date, when available.
    """

    possible_fields = [
        "scheduled_end",
    ]

    for field_name in possible_fields:
        value = getattr(
            maintenance,
            field_name,
            None,
        )

        if value is not None:
            return value

    return None


def is_active_maintenance(
    maintenance: MaintenanceOrder,
) -> bool:
    """
    Checks whether a maintenance activity is currently active.
    """

    status = normalize_value(
        maintenance.maintenance_status
    )

    active_statuses = {
        "active",
        "open",
        "in_progress",
        "in progress",
        "ongoing",
        "under_maintenance",
        "under maintenance",
        "scheduled",
        "pending",
    }

    return status in active_statuses


def is_completed_maintenance(
    maintenance: MaintenanceOrder,
) -> bool:
    """
    Checks whether a maintenance activity is completed.
    """

    status = normalize_value(
        getattr(
            maintenance,
            "status",
            None,
        )
    )

    completed_statuses = {
        "completed",
        "closed",
        "resolved",
        "cancelled",
        "canceled",
    }

    return status in completed_statuses


def is_maintenance_overdue(
    maintenance: MaintenanceOrder,
) -> bool:
    """
    Checks whether maintenance is overdue.
    """

    if is_completed_maintenance(maintenance):
        return False

    status = normalize_value(
        maintenance.maintenance_status
    )

    if status == "overdue":
        return True

    due_date = get_maintenance_due_date(
        maintenance
    )

    if due_date is None:
        return False

    now = datetime.now(timezone.utc)

    try:
        if due_date.tzinfo is None:
            due_date = due_date.replace(
                tzinfo=timezone.utc
            )

        return due_date < now

    except (TypeError, AttributeError):
        return False


@router.get("/summary")
async def get_dashboard_summary(
    db: AsyncSession = Depends(get_db),
):
    """
    Returns the main safety indicators required
    by the SurakshaAI dashboard.
    """

    # -----------------------------------------------------
    # 1. ACTIVE INCIDENTS
    # -----------------------------------------------------

    active_incidents_result = await db.execute(
        select(func.count(Incident.id)).where(
            Incident.status.notin_(
                [
                    "resolved",
                    "closed",
                ]
            )
        )
    )

    active_incidents = (
        active_incidents_result.scalar() or 0
    )

    # -----------------------------------------------------
    # 2. ACTIVE ALERTS
    # -----------------------------------------------------

    active_alerts_result = await db.execute(
        select(func.count(Alert.id)).where(
            Alert.status.notin_(
                [
                    "resolved",
                    "closed",
                ]
            )
        )
    )

    active_alerts = (
        active_alerts_result.scalar() or 0
    )

    # -----------------------------------------------------
    # 3. ACTIVE PERMITS
    # -----------------------------------------------------

    active_permits_result = await db.execute(
        select(func.count(Permit.id)).where(
            Permit.permit_status == "active"
        )
    )

    active_permits = (
        active_permits_result.scalar() or 0
    )

    # -----------------------------------------------------
    # 4. ACTIVE MAINTENANCE ORDERS
    # -----------------------------------------------------

    active_maintenance_result = await db.execute(
        select(
            func.count(MaintenanceOrder.id)
        ).where(
            MaintenanceOrder.maintenance_status.in_(
                [
                    "scheduled",
                    "in_progress",
                    "paused",
                ]
            )
        )
    )

    active_maintenance_orders = (
        active_maintenance_result.scalar() or 0
    )

    # -----------------------------------------------------
    # 5. LATEST RISK EVENT
    # -----------------------------------------------------

    latest_risk_result = await db.execute(
        select(RiskEvent)
        .order_by(
            RiskEvent.created_at.desc()
        )
        .limit(1)
    )

    latest_risk_event = (
        latest_risk_result.scalar_one_or_none()
    )

    # -----------------------------------------------------
    # 6. WORKERS CURRENTLY INSIDE
    # -----------------------------------------------------

    latest_locations_subquery = (
        select(
            WorkerLocation.worker_id,
            func.max(
                WorkerLocation.timestamp
            ).label("latest_timestamp"),
        )
        .group_by(
            WorkerLocation.worker_id
        )
        .subquery()
    )

    workers_inside_result = await db.execute(
        select(
            func.count(WorkerLocation.id)
        )
        .join(
            latest_locations_subquery,
            (
                WorkerLocation.worker_id
                == latest_locations_subquery.c.worker_id
            )
            & (
                WorkerLocation.timestamp
                == latest_locations_subquery.c.latest_timestamp
            ),
        )
        .where(
            WorkerLocation.entry_status == "inside"
        )
    )

    workers_inside = (
        workers_inside_result.scalar() or 0
    )

    # -----------------------------------------------------
    # 7. PPE COMPLIANCE
    # -----------------------------------------------------

    latest_ppe_subquery = (
        select(
            WorkerPPEStatus.worker_id,
            func.max(
                WorkerPPEStatus.timestamp
            ).label("latest_timestamp"),
        )
        .group_by(
            WorkerPPEStatus.worker_id
        )
        .subquery()
    )

    latest_ppe_result = await db.execute(
        select(WorkerPPEStatus)
        .join(
            latest_ppe_subquery,
            (
                WorkerPPEStatus.worker_id
                == latest_ppe_subquery.c.worker_id
            )
            & (
                WorkerPPEStatus.timestamp
                == latest_ppe_subquery.c.latest_timestamp
            ),
        )
    )

    latest_ppe_records = (
        latest_ppe_result.scalars().all()
    )

    total_ppe_records = len(
        latest_ppe_records
    )

    compliant_workers = 0

    for record in latest_ppe_records:
        is_compliant = all(
            [
                record.helmet_detected,
                record.safety_vest_detected,
                record.gloves_detected,
                record.goggles_detected,
                record.safety_shoes_detected,
            ]
        )

        if is_compliant:
            compliant_workers += 1

    if total_ppe_records > 0:
        ppe_compliance_percentage = round(
            (
                compliant_workers
                / total_ppe_records
            )
            * 100,
            2,
        )
    else:
        ppe_compliance_percentage = 0.0

    # -----------------------------------------------------
    # 8. RESPONSE
    # -----------------------------------------------------

    latest_risk_data = None

    if latest_risk_event is not None:
        latest_risk_data = {
            "id": latest_risk_event.id,
            "plant_id": (
                latest_risk_event.plant_id
            ),
            "zone_id": (
                latest_risk_event.zone_id
            ),
            "equipment_id": (
                latest_risk_event.equipment_id
            ),
            "risk_score": (
                latest_risk_event.risk_score
            ),
            "risk_level": (
                latest_risk_event.risk_level
            ),
            "predicted_event": (
                latest_risk_event.predicted_event
            ),
            "created_at": (
                latest_risk_event.created_at
            ),
        }

    return {
        "active_incidents": active_incidents,
        "active_alerts": active_alerts,
        "active_permits": active_permits,
        "active_maintenance_orders": (
            active_maintenance_orders
        ),
        "workers_inside": workers_inside,
        "ppe_compliance_percentage": (
            ppe_compliance_percentage
        ),
        "latest_risk_event": latest_risk_data,
    }
@router.get("/risk-by-zone")
async def get_risk_by_zone(
    limit: int = 20,
    db: AsyncSession = Depends(get_db),
):
    """
    Returns zone-wise risk analytics using
    stored RiskEvent records.
    """

    if limit < 1 or limit > 100:
        raise HTTPException(
            status_code=400,
            detail="limit must be between 1 and 100",
        )

    result = await db.execute(
        select(
            RiskEvent.plant_id,
            RiskEvent.zone_id,

            func.count(
                RiskEvent.id
            ).label(
                "total_risk_events"
            ),

            func.avg(
                RiskEvent.risk_score
            ).label(
                "average_risk_score"
            ),

            func.max(
                RiskEvent.risk_score
            ).label(
                "maximum_risk_score"
            ),

            func.sum(
                case(
                    (
                        RiskEvent.risk_level
                        == "critical",
                        1,
                    ),
                    else_=0,
                )
            ).label(
                "critical_event_count"
            ),

            func.sum(
                case(
                    (
                        RiskEvent.risk_level
                        == "high",
                        1,
                    ),
                    else_=0,
                )
            ).label(
                "high_event_count"
            ),

            func.sum(
                case(
                    (
                        RiskEvent.risk_level
                        == "warning",
                        1,
                    ),
                    else_=0,
                )
            ).label(
                "warning_event_count"
            ),

            func.max(
                RiskEvent.created_at
            ).label(
                "latest_event_time"
            ),
        )
        .group_by(
            RiskEvent.plant_id,
            RiskEvent.zone_id,
        )
        .order_by(
            desc(
                func.max(
                    RiskEvent.risk_score
                )
            )
        )
        .limit(limit)
    )

    rows = result.all()

    zones = []

    for row in rows:
        average_risk_score = round(
            float(
                row.average_risk_score or 0
            ),
            2,
        )

        maximum_risk_score = round(
            float(
                row.maximum_risk_score or 0
            ),
            2,
        )

        if maximum_risk_score >= 80:
            zone_risk_level = "critical"

        elif maximum_risk_score >= 60:
            zone_risk_level = "high"

        elif maximum_risk_score >= 30:
            zone_risk_level = "warning"

        else:
            zone_risk_level = "low"

        zones.append(
            {
                "plant_id": row.plant_id,
                "zone_id": row.zone_id,
                "total_risk_events": (
                    row.total_risk_events
                ),
                "average_risk_score": (
                    average_risk_score
                ),
                "maximum_risk_score": (
                    maximum_risk_score
                ),
                "zone_risk_level": (
                    zone_risk_level
                ),
                "critical_event_count": int(
                    row.critical_event_count or 0
                ),
                "high_event_count": int(
                    row.high_event_count or 0
                ),
                "warning_event_count": int(
                    row.warning_event_count or 0
                ),
                "latest_event_time": (
                    row.latest_event_time
                ),
            }
        )

    return {
        "total_zones": len(zones),
        "zones": zones,
    }
    
@router.get("/risk-trend")
async def get_risk_trend(
    days: int = 7,
    plant_id: str | None = None,
    zone_id: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    """
    Returns daily risk-event analytics for the selected
    number of days.

    Optional filters:

    - plant_id
    - zone_id
    """

    if days < 1 or days > 90:
        raise HTTPException(
            status_code=400,
            detail="days must be between 1 and 90",
        )

    end_time = datetime.utcnow()

    start_time = (
        end_time - timedelta(days=days)
    )

    query = (
        select(
            func.date(
                RiskEvent.created_at
            ).label("event_date"),
            func.count(
                RiskEvent.id
            ).label("total_events"),
            func.avg(
                RiskEvent.risk_score
            ).label("average_risk_score"),
            func.max(
                RiskEvent.risk_score
            ).label("maximum_risk_score"),
            func.sum(
                case(
                    (
                        RiskEvent.risk_level
                        == "critical",
                        1,
                    ),
                    else_=0,
                )
            ).label("critical_events"),
            func.sum(
                case(
                    (
                        RiskEvent.risk_level
                        == "high",
                        1,
                    ),
                    else_=0,
                )
            ).label("high_events"),
            func.sum(
                case(
                    (
                        RiskEvent.risk_level
                        == "warning",
                        1,
                    ),
                    else_=0,
                )
            ).label("warning_events"),
        )
        .where(
            RiskEvent.created_at >= start_time
        )
    )

    if plant_id is not None:
        query = query.where(
            RiskEvent.plant_id == plant_id
        )

    if zone_id is not None:
        query = query.where(
            RiskEvent.zone_id == zone_id
        )

    query = (
        query
        .group_by(
            func.date(
                RiskEvent.created_at
            )
        )
        .order_by(
            func.date(
                RiskEvent.created_at
            )
        )
    )

    result = await db.execute(query)

    rows = result.all()

    trend = []

    for row in rows:
        trend.append(
            {
                "date": row.event_date,
                "total_events": (
                    row.total_events or 0
                ),
                "average_risk_score": round(
                    float(
                        row.average_risk_score or 0
                    ),
                    2,
                ),
                "maximum_risk_score": round(
                    float(
                        row.maximum_risk_score or 0
                    ),
                    2,
                ),
                "critical_events": (
                    row.critical_events or 0
                ),
                "high_events": (
                    row.high_events or 0
                ),
                "warning_events": (
                    row.warning_events or 0
                ),
            }
        )

    return {
        "period_days": days,
        "plant_id": plant_id,
        "zone_id": zone_id,
        "start_time": start_time,
        "end_time": end_time,
        "data_points": len(trend),
        "trend": trend,
    }
    
@router.get("/risk-distribution")
async def get_risk_distribution(
    days: int = 30,
    plant_id: str | None = None,
    zone_id: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    """
    Returns the distribution of risk events by risk level.

    Optional filters:

    - number of days
    - plant ID
    - zone ID
    """

    if days < 1 or days > 365:
        raise HTTPException(
            status_code=400,
            detail="days must be between 1 and 365",
        )

    end_time = datetime.now(timezone.utc)
    start_time = end_time - timedelta(days=days)

    query = (
        select(
            RiskEvent.risk_level,
            func.count(
                RiskEvent.id
            ).label("event_count"),
        )
        .where(
            RiskEvent.created_at >= start_time
        )
    )

    if plant_id is not None:
        query = query.where(
            RiskEvent.plant_id == plant_id
        )

    if zone_id is not None:
        query = query.where(
            RiskEvent.zone_id == zone_id
        )

    query = (
        query
        .group_by(
            RiskEvent.risk_level
        )
        .order_by(
            RiskEvent.risk_level
        )
    )

    result = await db.execute(query)
    rows = result.all()

    counts = {
        "low": 0,
        "warning": 0,
        "high": 0,
        "critical": 0,
    }

    for row in rows:
        risk_level = (
            row.risk_level.value
            if hasattr(row.risk_level, "value")
            else str(row.risk_level)
        )

        risk_level = risk_level.lower()

        if risk_level in counts:
            counts[risk_level] = (
                row.event_count or 0
            )

    total_events = sum(counts.values())

    distribution = []

    for risk_level in [
        "low",
        "warning",
        "high",
        "critical",
    ]:
        event_count = counts[risk_level]

        if total_events > 0:
            percentage = round(
                (
                    event_count
                    / total_events
                )
                * 100,
                2,
            )
        else:
            percentage = 0.0

        distribution.append(
            {
                "risk_level": risk_level,
                "event_count": event_count,
                "percentage": percentage,
            }
        )

    return {
        "period_days": days,
        "plant_id": plant_id,
        "zone_id": zone_id,
        "start_time": start_time,
        "end_time": end_time,
        "total_events": total_events,
        "distribution": distribution,
    }
    
@router.get("/active-incidents")
async def get_active_incidents(
    plant_id: str | None = None,
    zone_id: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    """
    Returns all currently active incidents.

    Optional filters:
    - plant_id
    - zone_id
    """

    query = select(Incident)

    # Adjust these status values according to your Incident model.
    query = query.where(
        Incident.status.in_(
            [
                "open",
                "active",
                "in_progress",
            ]
        )
    )

    if plant_id is not None:
        query = query.where(
            Incident.plant_id == plant_id
        )

    if zone_id is not None:
        query = query.where(
            Incident.zone_id == zone_id
        )

    query = query.order_by(
        desc(Incident.created_at)
    )

    result = await db.execute(query)

    incidents = result.scalars().all()

    response_data = []

    for incident in incidents:
        severity = (
            incident.severity.value
            if hasattr(incident.severity, "value")
            else incident.severity
        )

        status = (
            incident.status.value
            if hasattr(incident.status, "value")
            else incident.status
        )

        response_data.append(
            {
                "incident_id": incident.id,
                "plant_id": incident.plant_id,
                "zone_id": incident.zone_id,
                "incident_type": getattr(
                    incident,
                    "incident_type",
                    None,
                ),
                "severity": severity,
                "status": status,
                "risk_score": getattr(
                    incident,
                    "risk_score",
                    None,
                ),
                "description": getattr(
                    incident,
                    "description",
                    None,
                ),
                "started_at": getattr(
                    incident,
                    "created_at",
                    None,
                ),
                "updated_at": getattr(
                    incident,
                    "updated_at",
                    None,
                ),
            }
        )

    return {
        "plant_id": plant_id,
        "zone_id": zone_id,
        "total_active_incidents": len(
            response_data
        ),
        "incidents": response_data,
    }
    
@router.get("/worker-safety")
async def get_worker_safety_dashboard(
    plant_id: str | None = None,
    zone_id: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    """
    Return each worker's latest location and PPE safety status.

    Important rules:
    - No PPE data means "not_verified", not "non_compliant".
    - PPE compliance percentage is calculated only from verified PPE records.
    - Missing exposure data is returned as "unknown".
    """

    # ---------------------------------------------------------
    # 1. Find the timestamp/order column for WorkerLocation
    # ---------------------------------------------------------

    location_order_column = None

    for column_name in [
        "timestamp",
        "recorded_at",
        "updated_at",
        "created_at",
        "entry_time",
        "id",
    ]:
        if hasattr(WorkerLocation, column_name):
            location_order_column = getattr(
                WorkerLocation,
                column_name,
            )
            break

    # ---------------------------------------------------------
    # 2. Fetch worker location records
    # ---------------------------------------------------------

    location_query = select(WorkerLocation)

    if (
        plant_id is not None
        and hasattr(WorkerLocation, "plant_id")
    ):
        location_query = location_query.where(
            WorkerLocation.plant_id == plant_id
        )

    if (
        zone_id is not None
        and hasattr(WorkerLocation, "zone_id")
    ):
        location_query = location_query.where(
            WorkerLocation.zone_id == zone_id
        )

    if location_order_column is not None:
        location_query = location_query.order_by(
            desc(location_order_column)
        )

    location_result = await db.execute(
        location_query
    )

    location_records = (
        location_result.scalars().all()
    )

    # ---------------------------------------------------------
    # 3. Keep only the latest location for each worker
    # ---------------------------------------------------------

    latest_locations = {}

    for location in location_records:

        worker_id = getattr(
            location,
            "worker_id",
            None,
        )

        if worker_id is None:
            continue

        if worker_id not in latest_locations:
            latest_locations[worker_id] = location

    # ---------------------------------------------------------
    # 4. Find timestamp/order column for WorkerPPEStatus
    # ---------------------------------------------------------

    ppe_order_column = None

    for column_name in [
        "timestamp",
        "recorded_at",
        "updated_at",
        "created_at",
        "inspection_time",
        "id",
    ]:
        if hasattr(WorkerPPEStatus, column_name):
            ppe_order_column = getattr(
                WorkerPPEStatus,
                column_name,
            )
            break

    # ---------------------------------------------------------
    # 5. Dashboard counters
    # ---------------------------------------------------------

    workers_data = []

    total_workers_inside = 0

    compliant_workers = 0
    non_compliant_workers = 0
    unverified_ppe_workers = 0

    workers_at_risk = 0

    # ---------------------------------------------------------
    # 6. Process each worker
    # ---------------------------------------------------------

    for worker_id, location in latest_locations.items():

        # -----------------------------------------------------
        # Determine whether the worker is inside the plant
        # -----------------------------------------------------

        if hasattr(location, "is_inside"):
            is_inside = bool(
                location.is_inside
            )

        elif hasattr(location, "inside_plant"):
            is_inside = bool(
                location.inside_plant
            )

        elif hasattr(location, "status"):
            is_inside = (
                str(location.status)
                .strip()
                .lower()
                in {
                    "inside",
                    "active",
                    "present",
                    "entered",
                }
            )

        else:
            # A current location record means the worker
            # is assumed to be inside and tracked.
            is_inside = True

        if not is_inside:
            continue

        total_workers_inside += 1

        # -----------------------------------------------------
        # Fetch latest PPE record
        # -----------------------------------------------------

        ppe_query = select(
            WorkerPPEStatus
        ).where(
            WorkerPPEStatus.worker_id == worker_id
        )

        if ppe_order_column is not None:
            ppe_query = ppe_query.order_by(
                desc(ppe_order_column)
            )

        ppe_query = ppe_query.limit(1)

        ppe_result = await db.execute(
            ppe_query
        )

        latest_ppe = (
            ppe_result.scalar_one_or_none()
        )

        # -----------------------------------------------------
        # PPE status handling
        # -----------------------------------------------------

        ppe_data_available = (
            latest_ppe is not None
        )

        ppe_compliant = None
        ppe_status = "not_verified"
        missing_ppe = []

        if latest_ppe is not None:

            # Try to read one supported compliance field.
            if hasattr(
                latest_ppe,
                "is_compliant",
            ):
                raw_ppe_compliance = (
                    latest_ppe.is_compliant
                )

                if raw_ppe_compliance is not None:
                    ppe_compliant = bool(
                        raw_ppe_compliance
                    )

            elif hasattr(
                latest_ppe,
                "ppe_compliant",
            ):
                raw_ppe_compliance = (
                    latest_ppe.ppe_compliant
                )

                if raw_ppe_compliance is not None:
                    ppe_compliant = bool(
                        raw_ppe_compliance
                    )

            elif hasattr(
                latest_ppe,
                "compliant",
            ):
                raw_ppe_compliance = (
                    latest_ppe.compliant
                )

                if raw_ppe_compliance is not None:
                    ppe_compliant = bool(
                        raw_ppe_compliance
                    )

            elif hasattr(
                latest_ppe,
                "status",
            ):
                ppe_status_value = str(
                    latest_ppe.status
                ).strip().lower()

                if ppe_status_value in {
                    "compliant",
                    "safe",
                    "complete",
                }:
                    ppe_compliant = True

                elif ppe_status_value in {
                    "non_compliant",
                    "non-compliant",
                    "unsafe",
                    "incomplete",
                }:
                    ppe_compliant = False

            # Read missing PPE list when available.
            if hasattr(
                latest_ppe,
                "missing_ppe",
            ):
                missing_ppe = (
                    latest_ppe.missing_ppe
                    or []
                )

            elif hasattr(
                latest_ppe,
                "missing_items",
            ):
                missing_ppe = (
                    latest_ppe.missing_items
                    or []
                )

            # Normalize missing PPE into a Python list.
            if isinstance(
                missing_ppe,
                str,
            ):
                missing_ppe = [
                    item.strip()
                    for item in missing_ppe.split(",")
                    if item.strip()
                ]

            elif not isinstance(
                missing_ppe,
                list,
            ):
                try:
                    missing_ppe = list(
                        missing_ppe
                    )
                except TypeError:
                    missing_ppe = []

            # If missing PPE is listed, the worker cannot
            # be considered compliant.
            if len(missing_ppe) > 0:
                ppe_compliant = False

            if ppe_compliant is True:
                ppe_status = "compliant"
                compliant_workers += 1

            elif ppe_compliant is False:
                ppe_status = "non_compliant"
                non_compliant_workers += 1

            else:
                ppe_status = "not_verified"
                unverified_ppe_workers += 1

        else:
            # No PPE record exists.
            unverified_ppe_workers += 1

        # -----------------------------------------------------
        # Read worker exposure level
        # -----------------------------------------------------

        exposure_level = getattr(
            location,
            "exposure_level",
            None,
        )

        if exposure_level is None:
            exposure_level = "unknown"

        normalized_exposure = (
            str(exposure_level)
            .strip()
            .lower()
        )

        # -----------------------------------------------------
        # Determine worker risk
        # -----------------------------------------------------

        ppe_risk = (
            ppe_compliant is False
        )

        environmental_risk = (
            normalized_exposure
            in {
                "high",
                "critical",
            }
        )

        worker_at_risk = (
            ppe_risk
            or environmental_risk
        )

        if worker_at_risk:
            workers_at_risk += 1

        # -----------------------------------------------------
        # Fetch worker details
        # -----------------------------------------------------

        worker_query = (
            select(Worker)
            .where(
                Worker.worker_id == worker_id
            )
            .limit(1)
        )

        worker_result = await db.execute(
            worker_query
        )

        worker = (
            worker_result.scalar_one_or_none()
        )

        worker_name = None

        if worker is not None:
            worker_name = (
                getattr(
                    worker,
                    "name",
                    None,
                )
                or getattr(
                    worker,
                    "full_name",
                    None,
                )
                or getattr(
                    worker,
                    "worker_name",
                    None,
                )
            )

        # -----------------------------------------------------
        # Find latest location timestamp
        # -----------------------------------------------------

        location_timestamp = None

        for field_name in [
            "timestamp",
            "recorded_at",
            "updated_at",
            "created_at",
            "entry_time",
        ]:
            if hasattr(
                location,
                field_name,
            ):
                location_timestamp = getattr(
                    location,
                    field_name,
                )

                if location_timestamp is not None:
                    break

        # -----------------------------------------------------
        # Find latest PPE timestamp
        # -----------------------------------------------------

        ppe_timestamp = None

        if latest_ppe is not None:
            for field_name in [
                "timestamp",
                "recorded_at",
                "updated_at",
                "created_at",
                "inspection_time",
            ]:
                if hasattr(
                    latest_ppe,
                    field_name,
                ):
                    ppe_timestamp = getattr(
                        latest_ppe,
                        field_name,
                    )

                    if ppe_timestamp is not None:
                        break

        # -----------------------------------------------------
        # Add worker to response
        # -----------------------------------------------------

        workers_data.append(
            {
                "worker_id": worker_id,
                "worker_name": worker_name,
                "plant_id": getattr(
                    location,
                    "plant_id",
                    plant_id,
                ),
                "zone_id": getattr(
                    location,
                    "zone_id",
                    zone_id,
                ),
                "is_inside": is_inside,
                "ppe_data_available": (
                    ppe_data_available
                ),
                "ppe_status": ppe_status,
                "ppe_compliant": (
                    ppe_compliant
                ),
                "missing_ppe": missing_ppe,
                "exposure_level": (
                    exposure_level
                ),
                "worker_at_risk": (
                    worker_at_risk
                ),
                "last_location_update": (
                    location_timestamp
                ),
                "last_ppe_update": (
                    ppe_timestamp
                ),
            }
        )

    # ---------------------------------------------------------
    # 7. Calculate PPE compliance percentage
    # ---------------------------------------------------------

    verified_ppe_workers = (
        compliant_workers
        + non_compliant_workers
    )

    if verified_ppe_workers > 0:
        ppe_compliance_percentage = round(
            (
                compliant_workers
                / verified_ppe_workers
            )
            * 100,
            2,
        )
    else:
        ppe_compliance_percentage = None

    # ---------------------------------------------------------
    # 8. Return dashboard response
    # ---------------------------------------------------------

    return {
        "plant_id": plant_id,
        "zone_id": zone_id,
        "total_workers_inside": (
            total_workers_inside
        ),
        "ppe_compliant_workers": (
            compliant_workers
        ),
        "ppe_non_compliant_workers": (
            non_compliant_workers
        ),
        "ppe_unverified_workers": (
            unverified_ppe_workers
        ),
        "workers_at_risk": (
            workers_at_risk
        ),
        "ppe_compliance_percentage": (
            ppe_compliance_percentage
        ),
        "workers": workers_data,
    }
    
@router.get("/machine-health")
async def get_machine_health_dashboard(
    plant_id: str | None = Query(
        default=None,
        description="Filter machines by plant ID",
    ),
    zone_id: str | None = Query(
        default=None,
        description="Filter machines by zone ID",
    ),
    db: AsyncSession = Depends(get_db),
):
    """
    Returns the latest health condition of machines.

    The endpoint combines:

    - machine-anomaly information
    - compound-risk events
    - equipment risk severity
    - maintenance status
    - overdue maintenance

    No duplicate machine-health table is created.
    """

    # -------------------------------------------------
    # 1. LOAD RISK EVENTS
    # -------------------------------------------------

    risk_query = select(RiskEvent)

    if plant_id is not None:
        risk_query = risk_query.where(
            RiskEvent.plant_id == plant_id
        )

    if zone_id is not None:
        risk_query = risk_query.where(
            RiskEvent.zone_id == zone_id
        )

    risk_result = await db.execute(
        risk_query
    )

    risk_events = list(
        risk_result.scalars().all()
    )

    # -------------------------------------------------
    # 2. LOAD MAINTENANCE RECORDS
    # -------------------------------------------------

    maintenance_result = await db.execute(
        select(MaintenanceOrder)
    )

    maintenance_records = list(
        maintenance_result.scalars().all()
    )

    # Maintenance filters are applied safely in Python
    # because model field names may vary.
    filtered_maintenance = []

    for maintenance in maintenance_records:
        maintenance_plant_id = getattr(
            maintenance,
            "plant_id",
            None,
        )

        maintenance_zone_id = getattr(
            maintenance,
            "zone_id",
            None,
        )

        if (
            plant_id is not None
            and maintenance_plant_id != plant_id
        ):
            continue

        if (
            zone_id is not None
            and maintenance_zone_id != zone_id
        ):
            continue

        filtered_maintenance.append(
            maintenance
        )

    # -------------------------------------------------
    # 3. COLLECT ALL MACHINE IDS
    # -------------------------------------------------

    machine_ids: set[str] = set()

    for event in risk_events:
        equipment_id = getattr(
            event,
            "equipment_id",
            None,
        )

        if equipment_id:
            machine_ids.add(
                str(equipment_id)
            )

    for maintenance in filtered_maintenance:
        equipment_id = (
            getattr(
                maintenance,
                "equipment_id",
                None,
            )
            or getattr(
                maintenance,
                "machine_id",
                None,
            )
            or getattr(
                maintenance,
                "asset_id",
                None,
            )
        )

        if equipment_id:
            machine_ids.add(
                str(equipment_id)
            )

    # -------------------------------------------------
    # 4. BUILD MACHINE HEALTH INFORMATION
    # -------------------------------------------------

    machines = []

    healthy_machines = 0
    warning_machines = 0
    critical_machines = 0
    machines_under_maintenance = 0
    maintenance_due = 0

    for machine_id in sorted(machine_ids):

        machine_risk_events = [
            event
            for event in risk_events
            if str(
                getattr(
                    event,
                    "equipment_id",
                    "",
                )
            )
            == machine_id
        ]

        machine_maintenance_records = []

        for maintenance in filtered_maintenance:
            maintenance_machine_id = (
                getattr(
                    maintenance,
                    "equipment_id",
                    None,
                )
                or getattr(
                    maintenance,
                    "machine_id",
                    None,
                )
                or getattr(
                    maintenance,
                    "asset_id",
                    None,
                )
            )

            if (
                maintenance_machine_id is not None
                and str(maintenance_machine_id)
                == machine_id
            ):
                machine_maintenance_records.append(
                    maintenance
                )

        # ---------------------------------------------
        # 4.1 LATEST RISK EVENT
        # ---------------------------------------------

        machine_risk_events.sort(
            key=lambda event: (
                get_event_timestamp(event)
                or datetime.min
            ),
            reverse=True,
        )

        latest_risk_event = (
            machine_risk_events[0]
            if machine_risk_events
            else None
        )

        # ---------------------------------------------
        # 4.2 LATEST MAINTENANCE RECORD
        # ---------------------------------------------

        machine_maintenance_records.sort(
            key=lambda maintenance: (
                get_maintenance_timestamp(
                    maintenance
                )
                or datetime.min
            ),
            reverse=True,
        )

        latest_maintenance = (
            machine_maintenance_records[0]
            if machine_maintenance_records
            else None
        )

        # ---------------------------------------------
        # 4.3 MACHINE LOCATION
        # ---------------------------------------------

        machine_plant_id = None
        machine_zone_id = None

        if latest_risk_event is not None:
            machine_plant_id = getattr(
                latest_risk_event,
                "plant_id",
                None,
            )

            machine_zone_id = getattr(
                latest_risk_event,
                "zone_id",
                None,
            )

        if latest_maintenance is not None:
            machine_plant_id = (
                machine_plant_id
                or getattr(
                    latest_maintenance,
                    "plant_id",
                    None,
                )
            )

            machine_zone_id = (
                machine_zone_id
                or getattr(
                    latest_maintenance,
                    "zone_id",
                    None,
                )
            )

        # ---------------------------------------------
        # 4.4 ANOMALY CONDITION
        # ---------------------------------------------

        anomaly_detected = False
        anomaly_score = None

        if latest_risk_event is not None:
            anomaly_detected = (
                contains_machine_anomaly(
                    latest_risk_event
                )
            )

            anomaly_score = (
                get_machine_anomaly_score(
                    latest_risk_event
                )
            )

        # ---------------------------------------------
        # 4.5 RISK CONDITION
        # ---------------------------------------------

        latest_risk_level = ""

        if latest_risk_event is not None:
            latest_risk_level = normalize_value(
                getattr(
                    latest_risk_event,
                    "risk_level",
                    None,
                )
            )

        latest_risk_score = None

        if latest_risk_event is not None:
            raw_risk_score = getattr(
                latest_risk_event,
                "risk_score",
                None,
            )

            if raw_risk_score is not None:
                try:
                    latest_risk_score = round(
                        float(raw_risk_score),
                        2,
                    )
                except (TypeError, ValueError):
                    latest_risk_score = None

        # ---------------------------------------------
        # 4.6 MAINTENANCE CONDITION
        # ---------------------------------------------

        under_maintenance = any(
            is_active_maintenance(
                maintenance
            )
            for maintenance
            in machine_maintenance_records
        )

        overdue_maintenance = any(
            is_maintenance_overdue(
                maintenance
            )
            for maintenance
            in machine_maintenance_records
        )

        maintenance_status = "not_scheduled"
        maintenance_due_date = None

        if latest_maintenance is not None:
            maintenance_status = (
                normalize_value(
                    getattr(
                        latest_maintenance,
                        "status",
                        None,
                    )
                )
                or "unknown"
            )

            maintenance_due_date = (
                get_maintenance_due_date(
                    latest_maintenance
                )
            )

        if overdue_maintenance:
            maintenance_status = "overdue"

        elif under_maintenance:
            maintenance_status = (
                "under_maintenance"
            )

        # ---------------------------------------------
        # 4.7 FINAL MACHINE HEALTH
        # ---------------------------------------------

        if under_maintenance:
            health_status = "under_maintenance"

        elif (
            latest_risk_level == "critical"
            or (
                latest_risk_score is not None
                and latest_risk_score >= 81
            )
            or (
                anomaly_score is not None
                and anomaly_score >= 80
            )
        ):
            health_status = "critical"

        elif (
            anomaly_detected
            or overdue_maintenance
            or latest_risk_level
            in {
                "warning",
                "high",
            }
            or (
                latest_risk_score is not None
                and latest_risk_score >= 41
            )
        ):
            health_status = "warning"

        else:
            health_status = "healthy"

        # ---------------------------------------------
        # 4.8 UPDATE TOTAL COUNTS
        # ---------------------------------------------

        if health_status == "healthy":
            healthy_machines += 1

        elif health_status == "warning":
            warning_machines += 1

        elif health_status == "critical":
            critical_machines += 1

        elif health_status == "under_maintenance":
            machines_under_maintenance += 1

        if overdue_maintenance:
            maintenance_due += 1

        # ---------------------------------------------
        # 4.9 MACHINE RESPONSE
        # ---------------------------------------------

        machines.append(
            {
                "machine_id": machine_id,
                "plant_id": machine_plant_id,
                "zone_id": machine_zone_id,
                "health_status": health_status,
                "anomaly_detected": (
                    anomaly_detected
                ),
                "anomaly_score": anomaly_score,
                "latest_risk_score": (
                    latest_risk_score
                ),
                "latest_risk_level": (
                    latest_risk_level or None
                ),
                "maintenance_status": (
                    maintenance_status
                ),
                "under_maintenance": (
                    under_maintenance
                ),
                "maintenance_overdue": (
                    overdue_maintenance
                ),
                "maintenance_due_date": (
                    maintenance_due_date
                ),
                "last_risk_update": (
                    get_event_timestamp(
                        latest_risk_event
                    )
                    if latest_risk_event
                    else None
                ),
                "last_maintenance_update": (
                    get_maintenance_timestamp(
                        latest_maintenance
                    )
                    if latest_maintenance
                    else None
                ),
            }
        )

    # Critical machines appear first in the frontend.
    health_priority = {
        "critical": 1,
        "warning": 2,
        "under_maintenance": 3,
        "healthy": 4,
    }

    machines.sort(
        key=lambda machine: (
            health_priority.get(
                machine["health_status"],
                5,
            ),
            machine["machine_id"],
        )
    )

    return {
        "plant_id": plant_id,
        "zone_id": zone_id,
        "total_machines": len(machines),
        "healthy_machines": healthy_machines,
        "warning_machines": warning_machines,
        "critical_machines": critical_machines,
        "machines_under_maintenance": (
            machines_under_maintenance
        ),
        "maintenance_due": maintenance_due,
        "machines": machines,
    }
    
@router.get("/emergency-response")
async def get_emergency_response_dashboard(
    plant_id: str | None = None,
    zone_id: str | None = None,
    incident_id: int | None = None,
    db: AsyncSession = Depends(get_db),
):
    """
    Returns emergency-response actions generated for incidents.

    Workflow:
    Risk Event
    -> Incident
    -> Alert
    -> Response Action
    -> Emergency Response Dashboard
    """

    # ---------------------------------------------------------
    # 1. LOAD RESPONSE ACTIONS
    # ---------------------------------------------------------

    query = select(ResponseAction)

    if plant_id is not None:
        query = query.where(
            ResponseAction.plant_id == plant_id
        )

    if zone_id is not None:
        query = query.where(
            ResponseAction.zone_id == zone_id
        )

    if incident_id is not None:
        query = query.where(
            ResponseAction.incident_id == incident_id
        )

    query = query.order_by(
        desc(ResponseAction.created_at)
    )

    result = await db.execute(query)

    response_actions = list(
        result.scalars().all()
    )

    # ---------------------------------------------------------
    # 2. DASHBOARD COUNTERS
    # ---------------------------------------------------------

    total_actions = len(response_actions)

    pending_actions = 0
    in_progress_actions = 0
    completed_actions = 0
    verified_actions = 0
    overdue_actions = 0
    critical_actions = 0
    mandatory_pending_actions = 0

    active_incident_ids = set()
    responder_names = set()
    assigned_roles = set()

    action_data = []

    now = datetime.now(timezone.utc)

    total_response_seconds = 0.0
    response_time_count = 0

    total_completion_seconds = 0.0
    completion_time_count = 0

    # ---------------------------------------------------------
    # 3. PROCESS EACH RESPONSE ACTION
    # ---------------------------------------------------------

    for action in response_actions:

        status = (
            action.status.value
            if hasattr(action.status, "value")
            else str(action.status)
        )

        status = status.strip().lower()

        priority = (
            action.priority.value
            if hasattr(action.priority, "value")
            else str(action.priority)
        )

        priority = priority.strip().lower()

        action_type = (
            action.action_type.value
            if hasattr(action.action_type, "value")
            else str(action.action_type)
        )

        action_type = action_type.strip().lower()

        # -----------------------------------------------------
        # STATUS COUNTS
        # -----------------------------------------------------

        if status in {
            "pending",
            "open",
            "assigned",
        }:
            pending_actions += 1

        elif status in {
            "in_progress",
            "in progress",
            "ongoing",
            "started",
        }:
            in_progress_actions += 1

        elif status in {
            "completed",
            "resolved",
            "closed",
        }:
            completed_actions += 1

        elif status in {
            "verified",
        }:
            completed_actions += 1
            verified_actions += 1

        if action.verified_at is not None:
            verified_actions += 1

        # Avoid double-counting verified actions.
        if (
            status == "verified"
            and action.verified_at is not None
        ):
            verified_actions -= 1

        # -----------------------------------------------------
        # CRITICAL ACTIONS
        # -----------------------------------------------------

        if priority in {
            "critical",
            "emergency",
            "urgent",
        }:
            critical_actions += 1

        # -----------------------------------------------------
        # OVERDUE ACTIONS
        # -----------------------------------------------------

        is_completed = status in {
            "completed",
            "resolved",
            "closed",
            "verified",
        }

        action_due_at = action.due_at

        if action_due_at is not None:
            if action_due_at.tzinfo is None:
                action_due_at = (
                    action_due_at.replace(
                        tzinfo=timezone.utc
                    )
                )

        is_overdue = (
            not is_completed
            and action_due_at is not None
            and action_due_at < now
        )

        if is_overdue:
            overdue_actions += 1

        # -----------------------------------------------------
        # MANDATORY PENDING ACTIONS
        # -----------------------------------------------------

        if (
            action.mandatory
            and not is_completed
        ):
            mandatory_pending_actions += 1

        # -----------------------------------------------------
        # ACTIVE INCIDENTS
        # -----------------------------------------------------

        if not is_completed:
            active_incident_ids.add(
                action.incident_id
            )

        # -----------------------------------------------------
        # RESPONDERS AND ROLES
        # -----------------------------------------------------

        if action.assigned_to:
            responder_names.add(
                action.assigned_to
            )

        if action.assigned_role:
            assigned_roles.add(
                action.assigned_role
            )

        # -----------------------------------------------------
        # RESPONSE TIME
        # created_at -> started_at
        # -----------------------------------------------------

        response_time_minutes = None

        if (
            action.created_at is not None
            and action.started_at is not None
        ):
            created_at = action.created_at
            started_at = action.started_at

            if created_at.tzinfo is None:
                created_at = created_at.replace(
                    tzinfo=timezone.utc
                )

            if started_at.tzinfo is None:
                started_at = started_at.replace(
                    tzinfo=timezone.utc
                )

            response_seconds = (
                started_at - created_at
            ).total_seconds()

            if response_seconds >= 0:
                total_response_seconds += (
                    response_seconds
                )

                response_time_count += 1

                response_time_minutes = round(
                    response_seconds / 60,
                    2,
                )

        # -----------------------------------------------------
        # COMPLETION TIME
        # started_at -> completed_at
        # -----------------------------------------------------

        completion_time_minutes = None

        if (
            action.started_at is not None
            and action.completed_at is not None
        ):
            started_at = action.started_at
            completed_at = action.completed_at

            if started_at.tzinfo is None:
                started_at = started_at.replace(
                    tzinfo=timezone.utc
                )

            if completed_at.tzinfo is None:
                completed_at = (
                    completed_at.replace(
                        tzinfo=timezone.utc
                    )
                )

            completion_seconds = (
                completed_at - started_at
            ).total_seconds()

            if completion_seconds >= 0:
                total_completion_seconds += (
                    completion_seconds
                )

                completion_time_count += 1

                completion_time_minutes = round(
                    completion_seconds / 60,
                    2,
                )

        # -----------------------------------------------------
        # FETCH INCIDENT DETAILS
        # -----------------------------------------------------

        incident_result = await db.execute(
            select(Incident)
            .where(
                Incident.id
                == action.incident_id
            )
            .limit(1)
        )

        incident = (
            incident_result.scalar_one_or_none()
        )

        incident_status = None
        incident_severity = None
        incident_type = None

        if incident is not None:

            incident_status = (
                incident.status.value
                if hasattr(
                    incident.status,
                    "value",
                )
                else incident.status
            )

            incident_severity = (
                incident.severity.value
                if hasattr(
                    incident.severity,
                    "value",
                )
                else incident.severity
            )

            incident_type = (
                incident.incident_type
            )

        # -----------------------------------------------------
        # FETCH ALERT DETAILS
        # -----------------------------------------------------

        alert_status = None
        alert_severity = None

        if action.alert_id is not None:

            alert_result = await db.execute(
                select(Alert)
                .where(
                    Alert.id == action.alert_id
                )
                .limit(1)
            )

            alert = (
                alert_result.scalar_one_or_none()
            )

            if alert is not None:

                alert_status = (
                    alert.status.value
                    if hasattr(
                        alert.status,
                        "value",
                    )
                    else alert.status
                )

                alert_severity = (
                    alert.severity.value
                    if hasattr(
                        alert.severity,
                        "value",
                    )
                    else alert.severity
                )

        # -----------------------------------------------------
        # EVACUATION IDENTIFICATION
        # -----------------------------------------------------

        evacuation_keywords = {
            "evacuation",
            "evacuate",
            "emergency evacuation",
            "zone evacuation",
        }

        combined_action_text = " ".join(
            [
                action_type,
                str(action.title or "").lower(),
                str(
                    action.description or ""
                ).lower(),
            ]
        )

        is_evacuation_action = any(
            keyword in combined_action_text
            for keyword in evacuation_keywords
        )

        # -----------------------------------------------------
        # ACTION RESPONSE
        # -----------------------------------------------------

        action_data.append(
            {
                "response_action_id": (
                    action.id
                ),
                "incident_id": (
                    action.incident_id
                ),
                "alert_id": action.alert_id,
                "plant_id": action.plant_id,
                "zone_id": action.zone_id,
                "equipment_id": (
                    action.equipment_id
                ),
                "action_type": action_type,
                "title": action.title,
                "description": (
                    action.description
                ),
                "priority": priority,
                "status": status,
                "assigned_role": (
                    action.assigned_role
                ),
                "assigned_to": (
                    action.assigned_to
                ),
                "mandatory": action.mandatory,
                "verification_required": (
                    action.verification_required
                ),
                "created_automatically": (
                    action.created_automatically
                ),
                "is_evacuation_action": (
                    is_evacuation_action
                ),
                "is_overdue": is_overdue,
                "incident_type": incident_type,
                "incident_status": (
                    incident_status
                ),
                "incident_severity": (
                    incident_severity
                ),
                "alert_status": alert_status,
                "alert_severity": (
                    alert_severity
                ),
                "completion_note": (
                    action.completion_note
                ),
                "verification_note": (
                    action.verification_note
                ),
                "completed_by": (
                    action.completed_by
                ),
                "verified_by": (
                    action.verified_by
                ),
                "response_time_minutes": (
                    response_time_minutes
                ),
                "completion_time_minutes": (
                    completion_time_minutes
                ),
                "created_at": (
                    action.created_at
                ),
                "due_at": action.due_at,
                "started_at": (
                    action.started_at
                ),
                "completed_at": (
                    action.completed_at
                ),
                "verified_at": (
                    action.verified_at
                ),
                "updated_at": (
                    action.updated_at
                ),
            }
        )

    # ---------------------------------------------------------
    # 4. CALCULATE AVERAGE TIMES
    # ---------------------------------------------------------

    if response_time_count > 0:
        average_response_time_minutes = round(
            (
                total_response_seconds
                / response_time_count
            )
            / 60,
            2,
        )
    else:
        average_response_time_minutes = None

    if completion_time_count > 0:
        average_completion_time_minutes = round(
            (
                total_completion_seconds
                / completion_time_count
            )
            / 60,
            2,
        )
    else:
        average_completion_time_minutes = None

    # ---------------------------------------------------------
    # 5. SORT ACTIONS
    # ---------------------------------------------------------

    priority_order = {
        "critical": 1,
        "emergency": 1,
        "urgent": 2,
        "high": 3,
        "medium": 4,
        "low": 5,
    }

    status_order = {
        "pending": 1,
        "open": 1,
        "assigned": 2,
        "in_progress": 3,
        "in progress": 3,
        "ongoing": 3,
        "started": 3,
        "completed": 4,
        "verified": 5,
        "resolved": 5,
        "closed": 5,
    }

    action_data.sort(
        key=lambda item: (
            status_order.get(
                item["status"],
                10,
            ),
            priority_order.get(
                item["priority"],
                10,
            ),
        )
    )

    # ---------------------------------------------------------
    # 6. RETURN DASHBOARD RESPONSE
    # ---------------------------------------------------------

    return {
        "plant_id": plant_id,
        "zone_id": zone_id,
        "incident_id": incident_id,
        "total_response_actions": total_actions,
        "active_emergencies": len(
            active_incident_ids
        ),
        "pending_actions": pending_actions,
        "in_progress_actions": (
            in_progress_actions
        ),
        "completed_actions": (
            completed_actions
        ),
        "verified_actions": verified_actions,
        "critical_actions": critical_actions,
        "overdue_actions": overdue_actions,
        "mandatory_pending_actions": (
            mandatory_pending_actions
        ),
        "responders_assigned": len(
            responder_names
        ),
        "assigned_roles_count": len(
            assigned_roles
        ),
        "assigned_roles": sorted(
            assigned_roles
        ),
        "average_response_time_minutes": (
            average_response_time_minutes
        ),
        "average_completion_time_minutes": (
            average_completion_time_minutes
        ),
        "actions": action_data,
    }
    
@router.get("/operations")
async def get_operations_dashboard(
    plant_id: str | None = None,
    zone_id: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    """
    Returns permit and maintenance operational statistics.
    """

    now = datetime.now(timezone.utc)

    # =========================================================
    # PERMIT QUERY
    # =========================================================

    permit_query = select(Permit)

    if plant_id is not None:
        permit_query = permit_query.where(
            Permit.plant_id == plant_id
        )

    if zone_id is not None:
        permit_query = permit_query.where(
            Permit.zone_id == zone_id
        )

    permit_query = permit_query.order_by(
        Permit.start_time.desc()
    )

    permit_result = await db.execute(
        permit_query
    )

    permits = list(
        permit_result.scalars().all()
    )

    # =========================================================
    # MAINTENANCE QUERY
    # =========================================================

    maintenance_query = select(
        MaintenanceOrder
    )

    if plant_id is not None:
        maintenance_query = maintenance_query.where(
            MaintenanceOrder.plant_id == plant_id
        )

    if zone_id is not None:
        maintenance_query = maintenance_query.where(
            MaintenanceOrder.zone_id == zone_id
        )

    maintenance_query = maintenance_query.order_by(
        MaintenanceOrder.reported_time.desc()
    )

    maintenance_result = await db.execute(
        maintenance_query
    )

    maintenance_orders = list(
        maintenance_result.scalars().all()
    )

    # =========================================================
    # PERMIT COUNTERS
    # =========================================================

    total_permits = len(permits)

    active_permits = 0
    expired_permits = 0
    closed_permits = 0
    cancelled_permits = 0
    upcoming_permits = 0
    high_risk_permits = 0
    hot_work_permits = 0
    confined_space_permits = 0
    invalid_isolation_permits = 0
    invalid_gas_test_permits = 0

    permit_data = []

    for permit in permits:
        permit_status = str(
            permit.permit_status or ""
        ).strip().lower()

        risk_level = str(
            permit.risk_level or ""
        ).strip().lower()

        start_time = permit.start_time
        expiry_time = permit.expiry_time

        if (
            start_time is not None
            and start_time.tzinfo is None
        ):
            start_time = start_time.replace(
                tzinfo=timezone.utc
            )

        if (
            expiry_time is not None
            and expiry_time.tzinfo is None
        ):
            expiry_time = expiry_time.replace(
                tzinfo=timezone.utc
            )

        is_time_active = (
            start_time is not None
            and expiry_time is not None
            and start_time <= now <= expiry_time
        )

        is_expired = (
            expiry_time is not None
            and expiry_time < now
            and permit_status not in {
                "closed",
                "cancelled",
            }
        )

        is_upcoming = (
            start_time is not None
            and start_time > now
            and permit_status not in {
                "closed",
                "cancelled",
            }
        )

        if (
            permit_status == "active"
            and is_time_active
        ):
            active_permits += 1

        if is_expired:
            expired_permits += 1

        if is_upcoming:
            upcoming_permits += 1

        if permit_status == "closed":
            closed_permits += 1

        if permit_status == "cancelled":
            cancelled_permits += 1

        if risk_level in {
            "high",
            "critical",
        }:
            high_risk_permits += 1

        if permit.hot_work_flag:
            hot_work_permits += 1

        if permit.confined_space_flag:
            confined_space_permits += 1

        isolation_issue = (
            permit.isolation_required
            and not permit.isolation_confirmed
        )

        if isolation_issue:
            invalid_isolation_permits += 1

        gas_test_issue = (
            permit.gas_test_required
            and permit.gas_test_value is None
        )

        if gas_test_issue:
            invalid_gas_test_permits += 1

        permit_data.append(
            {
                "permit_id": permit.permit_id,
                "plant_id": permit.plant_id,
                "zone_id": permit.zone_id,
                "equipment_id": permit.equipment_id,
                "permit_type": permit.permit_type,
                "work_description": (
                    permit.work_description
                ),
                "permit_status": permit_status,
                "risk_level": risk_level,
                "worker_count": permit.worker_count,
                "contractor_name": (
                    permit.contractor_name
                ),
                "hot_work": permit.hot_work_flag,
                "confined_space": (
                    permit.confined_space_flag
                ),
                "gas_test_required": (
                    permit.gas_test_required
                ),
                "gas_test_value": (
                    permit.gas_test_value
                ),
                "gas_test_issue": gas_test_issue,
                "isolation_required": (
                    permit.isolation_required
                ),
                "isolation_confirmed": (
                    permit.isolation_confirmed
                ),
                "isolation_issue": isolation_issue,
                "is_currently_active": (
                    permit_status == "active"
                    and is_time_active
                ),
                "is_expired": is_expired,
                "is_upcoming": is_upcoming,
                "start_time": permit.start_time,
                "expiry_time": permit.expiry_time,
                "issuer_id": permit.issuer_id,
                "approver_id": permit.approver_id,
            }
        )

    # =========================================================
    # MAINTENANCE COUNTERS
    # =========================================================

    total_maintenance_orders = len(
        maintenance_orders
    )

    scheduled_maintenance = 0
    in_progress_maintenance = 0
    paused_maintenance = 0
    completed_maintenance = 0
    overdue_maintenance = 0
    critical_maintenance = 0
    equipment_under_maintenance = set()
    lockout_tagout_pending = 0

    maintenance_data = []

    for order in maintenance_orders:
        maintenance_status = str(
            order.maintenance_status or ""
        ).strip().lower()

        equipment_status = str(
            order.equipment_status or ""
        ).strip().lower()

        criticality = str(
            order.criticality or ""
        ).strip().lower()

        scheduled_start = order.scheduled_start
        scheduled_end = order.scheduled_end

        if (
            scheduled_start is not None
            and scheduled_start.tzinfo is None
        ):
            scheduled_start = (
                scheduled_start.replace(
                    tzinfo=timezone.utc
                )
            )

        if (
            scheduled_end is not None
            and scheduled_end.tzinfo is None
        ):
            scheduled_end = scheduled_end.replace(
                tzinfo=timezone.utc
            )

        if maintenance_status == "scheduled":
            scheduled_maintenance += 1

        elif maintenance_status == "in_progress":
            in_progress_maintenance += 1

        elif maintenance_status == "paused":
            paused_maintenance += 1

        elif maintenance_status == "completed":
            completed_maintenance += 1

        is_completed = (
            maintenance_status == "completed"
        )

        is_overdue = (
            not is_completed
            and (
                order.maintenance_overdue_days > 0
                or (
                    scheduled_end is not None
                    and scheduled_end < now
                )
            )
        )

        if is_overdue:
            overdue_maintenance += 1

        if criticality in {
            "high",
            "critical",
        }:
            critical_maintenance += 1

        is_under_maintenance = (
            maintenance_status in {
                "scheduled",
                "in_progress",
                "paused",
            }
            or equipment_status in {
                "under_maintenance",
                "maintenance",
                "isolated",
                "shutdown",
            }
        )

        if is_under_maintenance:
            equipment_under_maintenance.add(
                order.equipment_id
            )

        lockout_issue = (
            order.lockout_tagout_required
            and not order.lockout_tagout_confirmed
        )

        if lockout_issue:
            lockout_tagout_pending += 1

        maintenance_data.append(
            {
                "work_order_id": (
                    order.work_order_id
                ),
                "plant_id": order.plant_id,
                "zone_id": order.zone_id,
                "equipment_id": (
                    order.equipment_id
                ),
                "maintenance_type": (
                    order.maintenance_type
                ),
                "failure_description": (
                    order.failure_description
                ),
                "maintenance_status": (
                    maintenance_status
                ),
                "equipment_status": (
                    equipment_status
                ),
                "criticality": criticality,
                "assigned_team": (
                    order.assigned_team
                ),
                "is_under_maintenance": (
                    is_under_maintenance
                ),
                "is_overdue": is_overdue,
                "maintenance_overdue_days": (
                    order.maintenance_overdue_days
                ),
                "lockout_tagout_required": (
                    order.lockout_tagout_required
                ),
                "lockout_tagout_confirmed": (
                    order.lockout_tagout_confirmed
                ),
                "lockout_tagout_issue": (
                    lockout_issue
                ),
                "reported_time": (
                    order.reported_time
                ),
                "scheduled_start": (
                    order.scheduled_start
                ),
                "scheduled_end": (
                    order.scheduled_end
                ),
                "actual_start": (
                    order.actual_start
                ),
                "actual_end": (
                    order.actual_end
                ),
            }
        )

    # =========================================================
    # RETURN RESPONSE
    # =========================================================

    return {
        "plant_id": plant_id,
        "zone_id": zone_id,

        "permit_summary": {
            "total_permits": total_permits,
            "active_permits": active_permits,
            "expired_permits": expired_permits,
            "upcoming_permits": upcoming_permits,
            "closed_permits": closed_permits,
            "cancelled_permits": (
                cancelled_permits
            ),
            "high_risk_permits": (
                high_risk_permits
            ),
            "hot_work_permits": (
                hot_work_permits
            ),
            "confined_space_permits": (
                confined_space_permits
            ),
            "isolation_issues": (
                invalid_isolation_permits
            ),
            "gas_test_issues": (
                invalid_gas_test_permits
            ),
        },

        "maintenance_summary": {
            "total_maintenance_orders": (
                total_maintenance_orders
            ),
            "scheduled_maintenance": (
                scheduled_maintenance
            ),
            "in_progress_maintenance": (
                in_progress_maintenance
            ),
            "paused_maintenance": (
                paused_maintenance
            ),
            "completed_maintenance": (
                completed_maintenance
            ),
            "overdue_maintenance": (
                overdue_maintenance
            ),
            "critical_maintenance": (
                critical_maintenance
            ),
            "machines_under_maintenance": len(
                equipment_under_maintenance
            ),
            "lockout_tagout_pending": (
                lockout_tagout_pending
            ),
        },

        "permits": permit_data,
        "maintenance_orders": maintenance_data,
    }
    
@router.get("/plant-map")
async def get_plant_map_dashboard(
    plant_id: str | None = None,
    floor_level: int | None = None,
    db: AsyncSession = Depends(get_db),
):
    """
    Returns plant-zone layout together with live safety data.

    It combines:
    - zone geometry
    - current risk
    - active incidents
    - active alerts
    - workers currently inside
    - active permits
    - active maintenance
    """

    # ---------------------------------------------------------
    # 1. LOAD PLANT ZONES
    # ---------------------------------------------------------

    zone_query = select(PlantZone)

    if plant_id is not None:
        zone_query = zone_query.where(
            PlantZone.plant_id == plant_id
        )

    if floor_level is not None:
        zone_query = zone_query.where(
            PlantZone.floor_level == floor_level
        )

    zone_query = zone_query.order_by(
        PlantZone.plant_id,
        PlantZone.floor_level,
        PlantZone.zone_name,
    )

    zone_result = await db.execute(
        zone_query
    )

    plant_zones = list(
        zone_result.scalars().all()
    )

    # ---------------------------------------------------------
    # 2. LOAD RELATED RECORDS
    # ---------------------------------------------------------

    risk_query = select(RiskEvent)
    incident_query = select(Incident)
    alert_query = select(Alert)
    worker_location_query = select(WorkerLocation)
    permit_query = select(Permit)
    maintenance_query = select(MaintenanceOrder)

    if plant_id is not None:
        risk_query = risk_query.where(
            RiskEvent.plant_id == plant_id
        )

        incident_query = incident_query.where(
            Incident.plant_id == plant_id
        )

        alert_query = alert_query.where(
            Alert.plant_id == plant_id
        )

        worker_location_query = (
            worker_location_query.where(
                WorkerLocation.plant_id == plant_id
            )
        )

        permit_query = permit_query.where(
            Permit.plant_id == plant_id
        )

        maintenance_query = (
            maintenance_query.where(
                MaintenanceOrder.plant_id == plant_id
            )
        )

    risk_result = await db.execute(
        risk_query.order_by(
            RiskEvent.created_at.desc()
        )
    )

    incident_result = await db.execute(
        incident_query
    )

    alert_result = await db.execute(
        alert_query
    )

    worker_location_result = await db.execute(
        worker_location_query.order_by(
            WorkerLocation.timestamp.desc()
        )
    )

    permit_result = await db.execute(
        permit_query
    )

    maintenance_result = await db.execute(
        maintenance_query
    )

    risk_events = list(
        risk_result.scalars().all()
    )

    incidents = list(
        incident_result.scalars().all()
    )

    alerts = list(
        alert_result.scalars().all()
    )

    worker_locations = list(
        worker_location_result.scalars().all()
    )

    permits = list(
        permit_result.scalars().all()
    )

    maintenance_orders = list(
        maintenance_result.scalars().all()
    )

    # ---------------------------------------------------------
    # 3. KEEP LATEST WORKER LOCATION
    # ---------------------------------------------------------

    latest_worker_locations = {}

    for location in worker_locations:
        if location.worker_id not in latest_worker_locations:
            latest_worker_locations[
                location.worker_id
            ] = location

    # ---------------------------------------------------------
    # 4. BUILD EACH ZONE
    # ---------------------------------------------------------

    now = datetime.now(timezone.utc)
    zones = []

    risk_priority = {
        "critical": 4,
        "high": 3,
        "warning": 2,
        "advisory": 1,
        "low": 0,
        "normal": 0,
    }

    for zone in plant_zones:
        zone_risk_events = [
            event
            for event in risk_events
            if (
                event.plant_id == zone.plant_id
                and event.zone_id == zone.zone_id
            )
        ]

        zone_incidents = [
            incident
            for incident in incidents
            if (
                incident.plant_id == zone.plant_id
                and incident.zone_id == zone.zone_id
                and normalize_value(
                    incident.status
                )
                not in {
                    "resolved",
                    "closed",
                }
            )
        ]

        zone_alerts = [
            alert
            for alert in alerts
            if (
                alert.plant_id == zone.plant_id
                and alert.zone_id == zone.zone_id
                and normalize_value(
                    alert.status
                )
                not in {
                    "resolved",
                    "closed",
                }
            )
        ]

        workers_inside = [
            location
            for location
            in latest_worker_locations.values()
            if (
                location.plant_id == zone.plant_id
                and location.zone_id == zone.zone_id
                and normalize_value(
                    location.entry_status
                )
                == "inside"
            )
        ]

        active_permits = []

        for permit in permits:
            if (
                permit.plant_id != zone.plant_id
                or permit.zone_id != zone.zone_id
            ):
                continue

            start_time = permit.start_time
            expiry_time = permit.expiry_time

            if (
                start_time is not None
                and start_time.tzinfo is None
            ):
                start_time = start_time.replace(
                    tzinfo=timezone.utc
                )

            if (
                expiry_time is not None
                and expiry_time.tzinfo is None
            ):
                expiry_time = expiry_time.replace(
                    tzinfo=timezone.utc
                )

            if (
                normalize_value(
                    permit.permit_status
                )
                == "active"
                and start_time is not None
                and expiry_time is not None
                and start_time <= now <= expiry_time
            ):
                active_permits.append(
                    permit
                )

        active_maintenance = [
            order
            for order in maintenance_orders
            if (
                order.plant_id == zone.plant_id
                and order.zone_id == zone.zone_id
                and normalize_value(
                    order.maintenance_status
                )
                in {
                    "scheduled",
                    "in_progress",
                    "paused",
                }
            )
        ]

        latest_risk_event = (
            zone_risk_events[0]
            if zone_risk_events
            else None
        )

        latest_risk_score = 0.0
        latest_risk_level = "low"
        latest_risk_time = None

        if latest_risk_event is not None:
            latest_risk_score = round(
                float(
                    latest_risk_event.risk_score
                    or 0
                ),
                2,
            )

            latest_risk_level = normalize_value(
                latest_risk_event.risk_level
            ) or "low"

            latest_risk_time = (
                latest_risk_event.created_at
            )

        highest_risk_level = latest_risk_level

        for event in zone_risk_events:
            event_level = normalize_value(
                event.risk_level
            )

            if (
                risk_priority.get(
                    event_level,
                    0,
                )
                > risk_priority.get(
                    highest_risk_level,
                    0,
                )
            ):
                highest_risk_level = event_level

        if zone_incidents:
            zone_status = "critical"

        elif (
            highest_risk_level
            in {
                "critical",
                "high",
            }
        ):
            zone_status = highest_risk_level

        elif zone_alerts:
            zone_status = "warning"

        elif active_maintenance:
            zone_status = "maintenance"

        else:
            zone_status = "normal"

        zones.append(
            {
                "id": zone.id,
                "plant_id": zone.plant_id,
                "zone_id": zone.zone_id,
                "zone_name": zone.zone_name,
                "zone_type": zone.zone_type,
                "floor_level": zone.floor_level,
                "geometry": zone.geometry,
                "latitude": zone.latitude,
                "longitude": zone.longitude,
                "description": zone.description,
                "zone_status": zone_status,
                "latest_risk_score": (
                    latest_risk_score
                ),
                "latest_risk_level": (
                    latest_risk_level
                ),
                "latest_risk_time": (
                    latest_risk_time
                ),
                "total_risk_events": len(
                    zone_risk_events
                ),
                "active_incidents": len(
                    zone_incidents
                ),
                "active_alerts": len(
                    zone_alerts
                ),
                "workers_inside": len(
                    workers_inside
                ),
                "active_permits": len(
                    active_permits
                ),
                "active_maintenance_orders": len(
                    active_maintenance
                ),
                "equipment_under_maintenance": sorted(
                    {
                        order.equipment_id
                        for order in active_maintenance
                    }
                ),
            }
        )

    # ---------------------------------------------------------
    # 5. MAP SUMMARY
    # ---------------------------------------------------------

    return {
        "plant_id": plant_id,
        "floor_level": floor_level,
        "total_zones": len(zones),
        "critical_zones": sum(
            1
            for zone in zones
            if zone["zone_status"] == "critical"
        ),
        "high_risk_zones": sum(
            1
            for zone in zones
            if zone["zone_status"] == "high"
        ),
        "warning_zones": sum(
            1
            for zone in zones
            if zone["zone_status"] == "warning"
        ),
        "maintenance_zones": sum(
            1
            for zone in zones
            if zone["zone_status"] == "maintenance"
        ),
        "normal_zones": sum(
            1
            for zone in zones
            if zone["zone_status"] == "normal"
        ),
        "zones": zones,
    }